#!/bin/sh

export ANDROID_NDK_API_LEVEL=30
export ANDROID_SDK_VERSION=30
export ANDROID_API_LEVEL=30
export ANDROID_BUILD_TOOLS_VERSION=33.0.1
export ANDROID_NDK_VERSION="25.2.9519653"
export ANDROID_CMAKE_VERSION="3.22.1"

export ANDROID_SDK_HOME="$HOME/Android/Sdk"
export ANDROID_HOME="$ANDROID_SDK_HOME/build-tools/$ANDROID_BUILD_TOOLS_VERSION"
export ANDROID_NDK_HOME="$ANDROID_SDK_HOME/ndk/$ANDROID_NDK_VERSION"
export ANDROID_NDK="$ANDROID_NDK_HOME"

